/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package at.phatbl.kash

val prompt = "$ "

fun main(args: Array<String>) {
    while(true) {
        print(prompt)
        val line = readLine()
        println(line)
    }
}
